db = {
    'left_forward': False,
    'right_forward': False,
    'left_backward': True,
    'right_backward': True,
    'left_motor_a': 12,
    'left_motor_b': 11,
    'left_motor_pwm': 35,
    'right_motor_a': 31,
    'right_motor_b': 33,
    'right_motor_pwm': 37,
    'trig': 18,
    'echo': 16,
    'track_left2': 0,
    'track_left1': 0,
    'track_center': 0,
    'track_right1': 0,
    'track_right2': 0,

}
