db = {
    'left_forward': False,
    'right_forward': False,
    'left_backward': True,
    'right_backward': True,
    'left_motor_a': 12,
    'left_motor_b': 11,
    'left_motor_pwm': 35,
    'right_motor_a': 15,
    'right_motor_b': 13,
    'right_motor_pwm': 37,
    'trig': 33,
    'echo': 31,
    'track_left2': 16,
    'track_left1': 18,
    'track_center': 22,
    'track_right1': 40,
    'track_right2': 32,

}
